chore: update and cleanup system-team links on webpage
eclipse-tractusx/eclipse-tractusx.github.io pull request #1001
Opened 2024-07-25 09:44 UTC by FaGru3n

## Description

Clean Up System-Team Links on Webpage

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-07-25 11:50 UTC, SebastianBezold approved these changes

2024-07-25 12:35 UTC, almadigabor requested changes
Just small changes I'd recommend.

2024-07-25 12:35 UTC, almadigabor commented on docs/getting-started.md
> +- contact Tractus-X project lead or the committers via [Matrix Chat](https://chat.eclipse.org/#/room/#tractusx:matrix.eclipse.org)
There is an ongoing project lead election, guess we can say it in plural too.

```suggestion
- Contact Tractus-X project leads or the committers via [Matrix Chat](https://chat.eclipse.org/#/room/#tractusx:matrix.eclipse.org)
```

2024-07-25 13:43 UTC, SebastianBezold approved these changes

2024-07-26 08:04 UTC, arnoweiss approved these changes

2024-07-26 12:16 UTC, Siegfriedk approved these changes

2024-07-29 06:14 UTC, merged