Docs(bp-kits):updated arc42 view
eclipse-tractusx/eclipse-tractusx.github.io pull request #1022
Opened 2024-08-23 04:54 UTC by Unsharm

## Description
In this pull request, we have updated the Architecture view of the Business Partner KIT.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-08-23 09:31 UTC, SujitMBRDI commented on docs-kits/kits/Business Partner Kit/Documentation BPDM/bpdm_arc42.md
>  -Currently there is no SME Application available
Can you please add space here between '-' and 'Currently there is no SME Application available'

2024-08-23 09:36 UTC, SujitMBRDI commented on docs-kits/kits/Business Partner Kit/Documentation BPDM/bpdm_arc42.md
> +### Roles, Rights, Permissions
Please make relevant sub headings here, currently `Roles, Rights, Permissions` should appear in same precision of heading `Authentication & Autorization`

2024-08-23 09:38 UTC, SujitMBRDI commented on docs-kits/kits/Business Partner Kit/Documentation BPDM/bpdm_arc42.md
> +## Risks and Technical Debts
Please remove tail space

2024-08-23 09:39 UTC, SujitMBRDI requested changes
Changes looks good to me, suggested some minor changes.

2024-08-27 06:04 UTC, SujitMBRDI approved these changes

2024-08-28 10:48 UTC, maximilianong approved these changes

2024-08-29 05:31 UTC, merged