Minutes office hours Oct. 18th
eclipse-tractusx/eclipse-tractusx.github.io pull request #1060
Opened 2024-10-18 13:44 UTC by lgblaumeiser

## Description
Minutes of the office hour on Oct., 18th 2024

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-10-19 11:32 UTC, stephanbcbauer requested changes
LGTM just one suggestion related the canceled new joiner session

2024-10-19 11:32 UTC, stephanbcbauer commented on blog-meeting-minutes/2024-10-18-community-hour.md
> +- Open Meetings page has been enhanced, there are now relevant links like to the board that is relevant, ...
```suggestion
- Open Meetings page has been enhanced, there are now relevant links like to the task board that is relevant and related release timelines
- Regular New Joiner meeting was canceled. If a session is needed, it needs to be requested
```

2024-10-21 09:32 UTC, lgblaumeiser commented on blog-meeting-minutes/2024-10-18-community-hour.md
> +- Open Meetings page has been enhanced, there are now relevant links like to the board that is relevant, ...
done

2024-10-21 09:54 UTC, stephanbcbauer approved these changes
LGTM ⇾ i don't miss any topics, maybe other @eclipse-tractusx/automotive-tractusx-committers ???

2024-10-21 15:24 UTC, merged