docs(e2e tutorial): adapt tutorial for tractus-x community days
eclipse-tractusx/eclipse-tractusx.github.io pull request #1097
Opened 2024-11-27 12:37 UTC by stephanbcbauer

## Description

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-11-29 11:39 UTC, evegufy requested changes
Issues:

https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/95

https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/152

2024-11-29 11:39 UTC, evegufy commented on docs/tutorials/e2e/connect/deployComponents.md
why not just link directly link to the [README.md from the umbrella](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/main/charts/umbrella/README.md)? To avoid double maintenance, it appears to be the same content.

2024-11-29 11:47 UTC, stephanbcbauer commented on docs/tutorials/e2e/connect/deployComponents.md
not exactly ;) yes some parts are redundant, you are right. But for the tutorial (focus local deployment, with cloned repository e.g) we just copied the parts we need. if someone wants more options, the readme is linked anyway at the beginning of the deployComponents file

2024-11-29 12:05 UTC, evegufy commented on docs/tutorials/e2e/connect/deployComponents.md
agree that the readme in the umbrella contains more information but, as far as I see, this document just contains less information, no different information (where I'd also question why - for instance - here wouldn't be needed more information about the OS specifics in regards to network setup).

I'd really prefer that you'd update the README.md in the umbrella or in general the documentation in umbrella so that it fits to what is needed for the tutorial instead of beginning such a double maintenance.

2024-12-19 07:38 UTC, stephanbcbauer commented
@evegufy I already deleted most of the content ⇾ not all, but it shouldn't confuse the people any more. Let's clean up the tutorial next year.

@matbmoser can you please have a look at this PR? Thanks

2024-12-19 07:41 UTC, matbmoser approved these changes

2024-12-19 07:41 UTC, merged