Fix/traceability-KIT hot fix
eclipse-tractusx/eclipse-tractusx.github.io pull request #1122
Opened 2024-12-19 12:52 UTC by LuisRickert

## Description

This PR corrects wrong information which were published and fixes some rendering issues. 

The described aspect model "Special Characteristics" in the section Development View/ Data Provider of the Traceability KIT is an deprecated version. This PR updates the descriptions. 

There were some tables which were not correctly rendered due to bad formatting, this issue is also fixed. 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-12-21 07:43 UTC, jSchuetz88 requested changes
Thank you @LuisRickert for providing the update in accordance to the changes of the aspect model. Only two points from my side:

- [ ] Could you add this fix, to the changelog of the Traceability Kit? v. 6.0.1 should be sufficient.
- [ ] In addition, I think it would make sense to include this change retrospectively to the version 24.12 too as this closes a current gap in the descriptions.

2025-01-13 09:48 UTC, LuisRickert commented
> Thank you @LuisRickert for providing the update in accordance to the changes of the aspect model. Only two points from my side:
> 
> * [ ]  Could you add this fix, to the changelog of the Traceability Kit? v. 6.0.1 should be sufficient.
> * [ ]  In addition, I think it would make sense to include this change retrospectively to the version 24.12 too as this closes a current gap in the descriptions.

Done, thank you for the review!

2025-01-15 15:26 UTC, LuisRickert commented
@jSchuetz88 @stephanbcbauer wrt to the failing 3rd Party Dependency Check: I saw that there is the [PR-1127](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1127) open which updates the Dependency file. Should i wait until it is merged and do a rebase or should i update the Dependency file myself ?

2025-01-16 11:49 UTC, stephanbcbauer commented
> @jSchuetz88 @stephanbcbauer wrt to the failing 3rd Party Dependency Check: I saw that there is the [PR-1127](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1127) open which updates the Dependency file. Should i wait until it is merged and do a rebase or should i update the Dependency file myself ?

It's up to you, :) I think we will merge #1127 tomorrow or Monday. @jSchuetz88 needs just to do a minor change ;)

2025-01-16 15:12 UTC, stephanbcbauer commented
@jSchuetz88 please check again.

I am still not happy about "importing the notice section", but this is not part of this PR :)

2025-02-10 19:46 UTC, stephanbcbauer commented
@jSchuetz88 , @LuisRickert you had a meeting couple of days ago? Was this PR part of it? What is missing? Right now there are some conflicts.

2025-02-10 19:47 UTC, stephanbcbauer requested changes
Please fix the conflicts. Overall, the PR looks good from my perspective ⇾ @jSchuetz88?

2025-02-11 08:04 UTC, jSchuetz88 approved these changes
Looks good to me. Thank you for including the requested changes.

2025-02-11 09:07 UTC, LuisRickert commented
fixed conflicts, 

> Please fix the conflicts. Overall, the PR looks good from my perspective ⇾ @jSchuetz88?

done

note I bumped the minor of your changes in the changelog to 2 since the date was later than our changes.

2025-02-18 20:02 UTC, stephanbcbauer approved these changes
LGTM

2025-02-18 20:02 UTC, merged