Chore/add detailed update process
eclipse-tractusx/eclipse-tractusx.github.io pull request #279
Opened 2023-06-27 15:51 UTC by LuisRickert

With this PR we improve the description of the "how to update a KIT" section by adding more information and detailed step description @maximilianong

2023-06-28 08:30 UTC, FaGru3n requested changes
Please remove any `SystemGuideOrg` related Pic's 
this is my personal TryOut Orga and should not be included into Eclipse Tractus X 😉

2023-06-28 08:57 UTC, LuisRickert commented
Sure thing!

2023-06-30 12:06 UTC, FaGru3n requested changes

2023-06-30 12:06 UTC, FaGru3n commented on docs/kit-process/processes/update-documentation.md
>  4. The Traktus-X Team will review your pull request
little typo `Traktus-X`

2023-06-30 12:25 UTC, LuisRickert commented
latest change: rebase onto main

2023-07-04 12:55 UTC, LuisRickert commented
@FaGru3n please review

2023-07-11 13:24 UTC, merged