(doc): Initial commit for Connector Kit and edc version 0.5.x
eclipse-tractusx/eclipse-tractusx.github.io pull request #289
Opened 2023-07-06 13:17 UTC by stephanbcbauer

## Description

This is the initial commit/preperation für the Connector Kit which represents the future version of the edc 0.5.x

- preperation for documentation 0.5.x edc
- cleanup files (deleted unused files)
- md linter (adapted broken files -> also outside the Connector Kit)

Information

- the changes within this PR will result in the "Next" section which is the future 3.2 section
- The changelog is still missing -> will be created by another PR

2023-07-06 15:29 UTC, LuisRickert requested changes
The Changelog got no updates. I think there were some version bumps. If these are not revelvant this is change request is obsolete.

2023-07-06 20:54 UTC, stephanbcbauer commented
> The Changelog got no updates. I think there were some version bumps. If these are not revelvant this is change request is obsolete.

Hey @LuisRickert the changes are relevant ;) changelog will be updated with another PR. This here is quite big and I just wanted to be fast :) I have to consolidate with the developers about the changes. And since the changes are on "Next" it should be OK for now. Just to get it merged.

2023-07-07 12:00 UTC, LuisRickert approved these changes

2023-07-10 06:50 UTC, stephanbcbauer commented
> 

And now it's updated :)

2023-07-13 12:59 UTC, merged