docs: Create trg-7-01.md
eclipse-tractusx/eclipse-tractusx.github.io pull request #302
Opened 2023-07-18 08:18 UTC by the-tatanka

New SECURITY.md vulnerability "policy".
First report vulnerabilities via a GitHub security advisory and then to the Eclipse security dashboard. This is agreed with the Eclipse security team.

The new SECURITY.md is shown in code below.

2023-07-19 08:50 UTC, AngelikaWittek reviewed
@the-tatanka 
line 72: update the SECURITY file in this repo, change the link to it and add it to the PR, then we have no pending changes

2023-07-21 12:31 UTC, AngelikaWittek requested changes
Please add the text of the new security file inline.

Important: 
Change the text of the security file, not everybody has the permissions to draft a security advisory, only committers and project contributors have it.

My suggestion as example: 
[SECURITY.md](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/files/12123581/SECURITY.md)

2023-07-27 12:28 UTC, the-tatanka commented
As discussed, every GitHub user can create GitHub draft vulnerabilites / draft security advisories. This is an extremely low barrier for security researchers.

2023-07-27 12:34 UTC, the-tatanka commented
Updated the SECURITY.md example

2023-08-08 10:19 UTC, AngelikaWittek requested changes
@the-tatanka 

Thanks for adopting the content. The point still is that normal Github users and contributors see another view of the security tab then the committers.
for this reason my recommondation for the section "Security file" is:

### SECURITY FILE

Use the template below for your SECURITY.md file.

__SECURITY.md:__

```md
## Reporting a Vulnerability

Please do **not** report security vulnerabilities through public GitHub issues.

Please report vulnerabilities to this repository via **GitHub security advisories** instead.

How? Inside affected repository --> security tab

for contributor:
--> Report a vulnerability

for committer:
--> advisories --> New draft security advisory

In severe cases, you can also report a found vulnerability via mail or eclipse issue here: https://www.eclipse.org/security/

See [Eclipse Foundation Vulnerability Reporting Policy](https://www.eclipse.org/projects/handbook/#vulnerability).
```

2023-08-16 07:37 UTC, AngelikaWittek approved these changes
Looks good to me.

2023-08-16 07:37 UTC, merged