fix(docs): updated documents for bpdm kit with TRG
eclipse-tractusx/eclipse-tractusx.github.io pull request #358
Opened 2023-08-25 14:22 UTC by SujitMBRDI

## Description

In this pull request, added CC BY 4.0 License for Adoption View, updated Change Log and updated adaption view considering TRG.

2023-08-28 12:28 UTC, SebastianBezold requested changes
Hi @SujitMBRDI,

I do have a small change request regarding html tag vs markdown syntax.
Also, could you please resolve the merge conflicts?

2023-08-28 12:28 UTC, SebastianBezold commented on docs-kits/kits/Business Partner Kit/page_changelog.md
> +<h3>Added</h3>
Instead of using html tags, please use the markdown headline syntax `###`. Docusaurus will translate this into the proper html tag and styling

2023-08-29 07:05 UTC, SujitMBRDI commented
> Hi @SujitMBRDI,
> 
> I do have a small change request regarding html tag vs markdown syntax. Also, could you please resolve the merge conflicts?

Done @SebastianBezold

2023-08-29 11:56 UTC, SebastianBezold approved these changes
Thanks for the changes!

2023-08-29 11:57 UTC, merged