docs: update TRG 2.5 - draft version of new metadata option repoCategory
eclipse-tractusx/eclipse-tractusx.github.io pull request #430
Opened 2023-10-24 14:28 UTC by tomaszbarwicki

PR to crate TRG 2.5  draft version with an update of new metadata repoCategory option in .tractusx.

2023-10-25 11:43 UTC, FaGru3n requested changes
just a either capital letters or small ones to describe the options for "repoCategory"

2023-10-25 11:43 UTC, FaGru3n commented on docs/release/trg-0/trg-2-5.md
> +"Special" is dedicated mostly to repositories described as Special Interest Group (repo name begins with "sig-").
Hi @tomaszbarwicki, I would use the same field descriptions.

If you start with "special"  then also use "special" in further descriptions or just a little point list:

- "special" is dedicated mostly to repositories described as Special Interest Group (repo name begins with "sig-")
- "support" for repositories which are neither products nor SIG but play vital role in overall ecosystem

2023-11-30 07:00 UTC, FaGru3n commented
Hi @tomaszbarwicki guess your PR is outdated, because of the current infromation that are presented on https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5

2023-12-05 12:16 UTC, tomaszbarwicki commented
> Hi @tomaszbarwicki guess your PR is outdated, because of the current infromation that are presented on https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5

That seems to be correct, closing this one.

2023-12-05 12:16 UTC, closed without merging