fix: copyright clarification for modular production KIT
eclipse-tractusx/eclipse-tractusx.github.io pull request #557
Opened 2023-12-13 13:50 UTC by dominikoeh

## Description

Clarification of copyright notice in the Modular Production KIT. The current release states 

> `Fraunhofer Institute of Optronics, System Technology and Image Exploitation (IOSB)`

where it should have been 

> `Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer IWU & Fraunhofer IOSB)`

@danielmiehle @maximilianong 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-12-18 08:51 UTC, FaGru3n commented
hi @dominikoeh thanks for your contribution, did also checked the Dependencies and licence information?

because it is not check marked? and also a little info you can request reviewers by adding them in the reviewer section 😉

2023-12-18 08:56 UTC, danielmiehle approved these changes

2023-12-18 08:56 UTC, maximilianong reviewed
Please no changes on the 23.12 - this one is released. You can change the file in the "next".

2023-12-18 09:04 UTC, maximilianong approved these changes
Talked to @danielmiehle - change is approved. 
No content change.

2023-12-21 09:12 UTC, wehrstedt-jan approved these changes

2024-01-22 08:31 UTC, FaGru3n requested changes
Hi, looke quite ok but some symbols seems a bit confusing why to change that in that way

FYI @AngelikaWittek,

could you maybe give us a hint which is the proper format in this way?

2024-01-22 08:31 UTC, FaGru3n commented on docs-kits/kits/Modular Production Kit/page_adoption-view.md
>  - SPDX-FileCopyrightText: 2023,Siemens AG
```suggestion
- SPDX-FileCopyrightText: 2023 Siemens AG
```

2024-01-22 08:31 UTC, FaGru3n commented on docs-kits/kits/Modular Production Kit/page_adoption-view.md
> +- SPDX-FileCopyrightText: 2023;Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer IWU & Fraunhofer IOSB & Fraunhofer IPA)
```suggestion
- SPDX-FileCopyrightText: 2023 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer IWU & Fraunhofer IOSB & Fraunhofer IPA)
```

following the tips and tricks on one of your  [TRG 7-7](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07#documentation)

2024-01-22 08:31 UTC, FaGru3n commented on docs-kits_versioned_docs/version-23.12/kits/Modular Production Kit/page_adoption-view.md
> +- SPDX-FileCopyrightText: 2023;Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer IWU & Fraunhofer IOSB & Fraunhofer IPA)
```suggestion
- SPDX-FileCopyrightText: 2023 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer IWU & Fraunhofer IOSB & Fraunhofer IPA)
```

2024-01-22 08:31 UTC, FaGru3n commented on docs-kits_versioned_docs/version-23.12/kits/Modular Production Kit/page_adoption-view.md
>  - SPDX-FileCopyrightText: 2023,Siemens AG
```suggestion
- SPDX-FileCopyrightText: 2023 Siemens AG
```

2024-02-05 07:57 UTC, FaGru3n approved these changes
LGTM

2024-02-13 14:40 UTC, maximilianong approved these changes

2024-02-13 14:41 UTC, merged