fix: Update API health check commands and add JSON parsing with jq
eclipse-tractusx/eclipse-tractusx.github.io pull request #570
Opened 2023-12-19 11:50 UTC by awellnitz-materna

## Description
We were able to gather many impressions at the first TractusX Community Days. This also resulted in some suggestions for improvement.

With this PR we want to integrate the following suggestions.
- Executable commands should be in separate lines so that they can be easily copied on the website
- jq should be appended to the end of the whole reuqest as in MXD, this improves readability

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-01-21 20:28 UTC, stephanbcbauer submitted a review, later dismissed
LGTM

2024-01-21 20:31 UTC, stephanbcbauer commented
@florianrusch-zf we would need a second reviewer ;) for the tutorials

2024-01-23 06:57 UTC, florianrusch-zf approved these changes

2024-01-23 06:57 UTC, florianrusch-zf commented on docs/tutorials/e2e/connect/deployComponents.md
> +```
```suggestion
```
```

2024-01-23 06:57 UTC, florianrusch-zf commented on docs/tutorials/e2e/connect/deployComponents.md
> +```
```suggestion
```
```

2024-01-23 07:04 UTC, florianrusch-zf requested changes
Sorry, I just wanted to remove the spaces and not the code fences 😅 the suggestion syntax is a little bit confusing regarding changing code fences

2024-01-23 07:04 UTC, florianrusch-zf commented on docs/tutorials/e2e/connect/deployComponents.md
>  kind create cluster -n mxd --config kind.config.yaml
````suggestion
kind create cluster -n mxd --config kind.config.yaml
```
````

2024-01-23 07:04 UTC, florianrusch-zf commented on docs/tutorials/e2e/connect/deployComponents.md
>  cd <path/of/mxd>
````suggestion
```shell
cd <path/of/mxd>
````

2024-01-23 07:05 UTC, awellnitz-materna commented on docs/tutorials/e2e/connect/deployComponents.md
>  kind create cluster -n mxd --config kind.config.yaml
I have also just seen the pipeline :D

2024-01-23 07:05 UTC, florianrusch-zf commented on docs/tutorials/e2e/connect/deployComponents.md
>  cd <path/of/mxd>
````suggestion
cd <path/of/mxd>
```
````

2024-01-23 07:09 UTC, florianrusch-zf requested changes

2024-01-23 07:09 UTC, florianrusch-zf commented on docs/tutorials/e2e/connect/deployComponents.md
> +```shell
Just to keep it consistent
````suggestion

```shell
````

2024-01-23 07:09 UTC, florianrusch-zf commented on docs/tutorials/e2e/connect/deployComponents.md
> +```shell
````suggestion

```shell
````

2024-01-23 07:16 UTC, awellnitz-materna reviewed
Now it looks good again 😄

2024-01-23 07:16 UTC, florianrusch-zf approved these changes

2024-01-23 07:26 UTC, stephanbcbauer approved these changes
LGTM

2024-01-23 07:26 UTC, merged