docs(trg): make dedicated container image notice mandatory
eclipse-tractusx/eclipse-tractusx.github.io pull request #629
Opened 2024-01-23 13:05 UTC by SebastianBezold

## Description

This PR is a follow up to a [discussion on our mailing list](https://www.eclipse.org/lists/tractusx-dev/msg00306.html).
The discussion is about making a dedicated "Notice for Docker image" mandatory and no longer allow it to be a section in the top-level `README.md`.
So far, there has only been feedback pro change.

TL;DR from the discussion:

- Moving to a dedicated file is not a lot of work
- Can be used to better address target audience
- There is a character limit for DockerHub descriptions, which might cut off the mandatory notice section at the end of long repository README.md files

Fixes eclipse-tractusx/sig-infra#360

2024-01-23 14:51 UTC, FaGru3n approved these changes
LGTM only name for separate Docker `notice.md` could be discussed, i personally like the approach form "Country Risk" to name it "Docker_Notice.md"

2024-01-23 15:28 UTC, florianrusch-zf requested changes

2024-01-23 15:28 UTC, florianrusch-zf commented on docs/release/trg-4/trg-4-06.md
> +- Use "Container images" as headline to link to the container image notice files
```suggestion
- Use "Container images" as headline to link to the container image notice files from the repositories README.md file
```

2024-01-23 15:28 UTC, florianrusch-zf commented on docs/release/trg-4/trg-4-06.md
> +- [edc-controlplane-memory-hashicorp-vault](https://github.com/eclipse-tractusx/tractusx-edc/edit/main/edc-controlplane/edc-controlplane-memory-hashicorp-vault/notice.md)
```suggestion
- [edc-controlplane-memory-hashicorp-vault](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/edc-controlplane/edc-controlplane-memory-hashicorp-vault/notice.md)
```

2024-01-24 08:46 UTC, SebastianBezold commented on docs/release/trg-4/trg-4-06.md
> +# DockerHub publishing worklflow
Thanks for spotting! All suggestions good and added via [8d76080](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/629/commits/8d76080b37b110c520e86977c7e48ee5e5f2a440)

2024-01-24 08:52 UTC, FaGru3n approved these changes
LGTM

2024-02-08 14:31 UTC, carslen approved these changes
LGTM

2024-02-08 17:50 UTC, florianrusch-zf approved these changes

2024-02-08 18:34 UTC, merged