chore: New UX Consistency TRG DRAFT
eclipse-tractusx/eclipse-tractusx.github.io pull request #636
Opened 2024-01-24 12:12 UTC by kelaja

This TRG DRAFT can be used for defining the UX consistency tractus-x release guidelines (TRG)

2024-01-24 12:34 UTC, kelaja commented
Perspectively all Catena-X specific Intellectual Property need to be removed from tractus-x release guidelines.
One suggestion is to exchange the Catena-X logo with tracts-x logo.
Links to closed systems like figma need to be removed due to missing licence, open source alternative should be found.

2024-02-27 13:46 UTC, danielmiehle commented
@kelaja @jjeroch : is this PR still relevant or can we close it?

2024-03-19 09:36 UTC, kelaja reviewed
chore: TRG Draft for UX Guidelines

2024-03-19 09:46 UTC, kelaja reviewed
chore: new UX TRG

2024-03-19 15:16 UTC, RolaH1t commented on docs/release/trg-0/trg-1-09.md
> +title: TRG 1.09 - UX consistency Style Guideline for UI
UX consistency / Styleguide

2024-03-19 15:17 UTC, RolaH1t commented on docs/release/trg-0/trg-1-09.md
> +- UX consistency is mandatory for FrontEnd modules.
...is essential...

2024-03-19 15:17 UTC, RolaH1t commented on docs/release/trg-0/trg-1-09.md
> +- User Interfaces should align with the Catena-X Style Guidelines.
...therefore should adhere to the Tractus-X style guidelines.

2024-03-19 15:18 UTC, RolaH1t commented on docs/release/trg-0/trg-1-09.md
> +
delete line items 23 to 27

2024-03-19 15:20 UTC, RolaH1t commented on docs/release/trg-0/trg-1-09.md
> +
Make use of the public available shared component library (react supported) to easily develop applications that are in line with the Tractus-X style guidelines.

2024-03-19 15:21 UTC, RolaH1t commented on docs/release/trg-0/trg-1-09.md
> +
consolidate and update all relevant LINKs

2024-03-19 15:21 UTC, RolaH1t commented on docs/release/trg-0/trg-1-09.md
> +Please note, you can use the official public available CX shared component library (react supported) to easily develop applications that are in-line with the CX style guidelines.
delete line item 43

2024-03-19 15:22 UTC, RolaH1t commented
Pls help to wrap this up and officially utilize the new TRG for Release 24.05

2024-03-20 08:18 UTC, FaGru3n requested changes

2024-03-20 08:18 UTC, FaGru3n commented on docs/release/trg-0/trg-1-09.md
> +title: TRG 1.09 - UX consistency Style Guideline for UI
Hi @RolaH1t  you can directly share a suggestion for the code within this pr like: 
```suggestion
title: TRG 1.09 - UX consistency / Styleguide for UI
```

2024-03-20 08:18 UTC, FaGru3n commented on docs/release/trg-0/trg-1-09.md
> +| Draft - MISSING CLOSED INFORMATION      | 10-Jan-2024     | Transfered from Release Acceptance Criteria into TRG|
```suggestion
| Draft | 10-Jan-2024     | Transfered from Release Acceptance Criteria into TRG|
```

2024-03-20 08:18 UTC, FaGru3n commented on docs/release/trg-0/trg-1-09.md
> +- User Interfaces should align with the Catena-X Style Guidelines.
```suggestion
- User Interfaces **should** align with the Tractus-X Style Guidelines.
```

2024-03-21 15:57 UTC, jjeroch commented
@kelaja @RolaH1t & @danielmiehle what about merging this so that I can create my PR with the new content?

2024-03-21 16:22 UTC, RolaH1t commented
> @kelaja @RolaH1t & @danielmiehle what about merging this so that I can create my PR with the new content?

ok from my side

2024-03-26 17:00 UTC, kelaja commented
@jjeroch @FaGru3n there seems to be a check failing which prevents merging. Kindly guide how this can be fixed.

2024-03-27 07:47 UTC, FaGru3n commented
> @jjeroch @FaGru3n there seems to be a check failing which prevents merging. Kindly guide how this can be fixed.

https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03#checking-contributions-by-a-eclipse-contributor

2024-04-03 15:52 UTC, Siegfriedk commented
Introducing this TRG in my branch due to @kelaja being away for a bit and im unable to merge this PR due to a conflict @kelaja would need to fix.

2024-04-03 15:52 UTC, closed without merging