doc: Security TRG 8.0
eclipse-tractusx/eclipse-tractusx.github.io pull request #657
Opened 2024-02-09 10:31 UTC by klaudiaZF

## Description

This PR brings enhancement to the existing TRG with a new addition of TRG 8.0 for Security specific topics.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-02-09 11:59 UTC, FaGru3n requested changes
Hi @klaudiaZF,

thanks for your work so far an adopting the changes directlyt to our eclipse tractus-x webpage

feedback:

- trg 8-3 is IMHO a guideline how to use your repo and how to contact you and i would move it to the README.md for sig-security and link it in the general overview for security related TRG´s 

- for the other to new TRG´s (Tractus-X Release Guidelines) i questioned myself, is this full needed for the upcomming release or is this just an information, how to use the security tools and process to check? IMHO such information which tools we have to use should be explicit mentioned as "you have to" like should / must do this for the release.

- did you checked also the 
> - [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs. 

Thanks in advance.

2024-02-13 10:29 UTC, klaudiaZF commented
Thank you for your feedback

@FaGru3n trg 8-3 is providing a steps and in our README file we have only information and links

2024-02-14 09:11 UTC, SebastianBezold requested changes
In addition to my comments, I think the filenames should be adjusted.
We are building a website from this content and spaces in filenames always need to be encoded and are then hard to link. 

suggestion: kebap-case

2024-02-14 09:11 UTC, SebastianBezold commented on docs/release/trg-8/TRG 8.03 Security Support.md
This is definitely not content, that is meant to be defined as a release guideline. This sounds more like a contribution guideline to `sig-security`.

My proposal would be to introduce a "Special Interest Groups" section in "Community". This would be a much better place to introduce sig-security and the general working and contributing process. 

Maybe I'll start doing the skeleton for a "sig" section in "community". If so, i'll link the PR here

2024-02-14 16:22 UTC, evegufy commented on docs/release/trg-8/TRG 8.01 Security Scanning Toolchain.md
> +- **Container Scanner**: open-source: Trivy
Thank you for your contribution!
IMO each of those points could be TRG with a clear description of what each entails, for instance shortly outlining what SAST is, describing the available tooling and the quality gate criteria, like no critical or high finding as we're currently already living it.

2024-02-16 13:04 UTC, closed without merging