doc(open meetings): add new open meeting for edc weekly
eclipse-tractusx/eclipse-tractusx.github.io pull request #679
Opened 2024-02-16 10:29 UTC by stephanbcbauer

## Description
This PR adds a new open meeting to our open meetings page. An ICS file was not provided yet. Requester for this change is @stefan-ettl  and @be

<img width="963" alt="image" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/84396022/f2c2fce5-fcaa-4f46-ac67-f010fb562216">

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-02-16 10:37 UTC, stephanbcbauer commented
Can someone support here? @FaGru3n , @SebastianBezold ? I ran the dependency check locally, but I think it's a different result? Thanks for support

2024-02-16 10:48 UTC, SebastianBezold commented
> Can someone support here? @FaGru3n , @SebastianBezold ? I ran the dependency check locally, but I think it's a different result? Thanks for support

I had the check fail on a different PR too, but this was due to a technical issue with ClearlyDefined. Re-run worked without issue. Seems to be the case here as well

2024-02-16 10:49 UTC, SebastianBezold approved these changes

2024-02-16 11:01 UTC, FaGru3n approved these changes
LGTM

2024-02-16 13:36 UTC, stephanbcbauer commented
@stefan-ettl, @benwestphal could you please review from content perspective? Thanks

2024-02-16 15:07 UTC, FaGru3n submitted a review, later dismissed

2024-02-19 08:55 UTC, stefan-ettl approved these changes

2024-02-19 09:00 UTC, stephanbcbauer commented
[heart]         Stephan Bauer reacted to your message:
________________________________
From: Stefan Ettl ***@***.***>
Sent: Monday, February 19, 2024 8:56:00 AM
To: eclipse-tractusx/eclipse-tractusx.github.io ***@***.***>
Cc: Stephan Bauer ***@***.***>; Author ***@***.***>
Subject: Re: [eclipse-tractusx/eclipse-tractusx.github.io] doc(open meetings): add new open meeting for edc weekly (PR #679)


@stefan-ettl approved this pull request.

—
Reply to this email directly, view it on GitHub<https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/679#pullrequestreview-1887873259>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AUD4P5SB5FHAE6WHXEJUUQ3YUMHSBAVCNFSM6AAAAABDLZLFGSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBXHA3TGMRVHE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-02-19 09:04 UTC, carslen requested changes

2024-02-19 09:04 UTC, carslen commented on community/open-meetings.mdx
> +             schedule="Eevery 2 weeks on Friday effective 16. Feb 2024 until 31. Dec 2024 from 02:05 pm to 03:00 pm CET"
```suggestion
             schedule="Every 2 weeks on Friday effective 16. Feb 2024 until 31. Dec 2024 from 02:05 pm to 03:00 pm CET"
```

2024-02-19 09:04 UTC, carslen commented on community/open-meetings.mdx
> +             schedule="Eevery 2 weeks on Friday effective 16. Feb 2024 until 31. Dec 2024 from 02:05 pm to 03:00 pm CET"
Fix typo

2024-02-19 09:06 UTC, FaGru3n approved these changes

2024-02-19 09:15 UTC, carslen approved these changes
👍

2024-02-21 08:28 UTC, merged