fix: Markdownlint
eclipse-tractusx/eclipse-tractusx.github.io pull request #702
Opened 2024-02-20 21:49 UTC by bcronin90

Fix markdownlint issues

Closes #692 

MD053 in adoption-view.md looks like a false positive to me.

2024-02-21 07:25 UTC, stephanbcbauer submitted a review, later dismissed
LGTM, but please check if the title or id is used for header generation. THX

2024-02-21 07:25 UTC, stephanbcbauer commented on docs-kits/kits/Connector Kit/Adoption View/adoption-view.md
> -title: Adoption View
@bcronin90 have you checked if the title is used for the header 1? Or if it's the ID? Did you build it locally?

<img width="394" alt="image" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/84396022/cb1b2461-3668-4281-8c1b-21c6dc44ec88">

2024-02-21 07:25 UTC, stephanbcbauer commented on docs-kits/kits/Connector Kit/Development View/architecture.md
> -title: Architecture
same here, i am not sure if the title is used for the headline?

2024-02-21 10:32 UTC, mhellmeier requested changes
The build of the website fails which should be fixed before merging.

2024-02-21 15:17 UTC, stephanbcbauer commented on docs-kits/kits/Connector Kit/Operation View/operation-view.md
> +is: Operation View
is -> id

2024-02-21 16:26 UTC, bcronin90 commented
The "title" field is used for the headline, which is why it caused duplication warnings in the linter. The "id" field is purely for under-the-hood stuff. While I was removing the titles, I added ids where there weren't any. Apparently that broke something somewhere. So I'll revert that.

2024-02-22 12:44 UTC, SebastianBezold approved these changes

2024-02-22 12:49 UTC, bcronin90 commented
So what about this one?
```
docs-kits/kits/Connector Kit/Adoption View/adoption-view.md:152:1 MD053/link-image-reference-definitions Link and image reference definitions should be needed [Unused link or image reference definition: "dsp-url"] [Context: "[dsp-url]: https://docs.intern.../"]
```
Turns out it's not a false positive, just a bit misleading. We had a wrong bracket type in there. Yay for linting.

2024-02-22 13:00 UTC, bcronin90 commented
Okay, all Markdown errors should be from outside our scope now.

2024-02-22 14:36 UTC, bcronin90 commented
Might be something in one of the sidebars js'

2024-02-23 08:48 UTC, mhellmeier requested changes
This PR removes the title in different files. Therefore, it doesn't get displayed with an uppercase starting letter. This has nothing to do with the sidebar file.

2024-02-23 08:48 UTC, mhellmeier commented on docs-kits/kits/Connector Kit/Development View/architecture.md
> -title: Architecture
Removing the title will cause a wrong display in the menu.

2024-02-23 08:53 UTC, bcronin90 commented
> This PR removes the title in different files. Therefore, it doesn't get displayed with an uppercase starting letter. This has nothing to do with the sidebar file.

So what's the best practice here? Cause if I add it again, I get the duplicate header warning from the markdown linter, which this was supposed to remove. I can remove the actual markdown header instead. But instead of stumbling in the dark some more, I'll just ask: What's our general approach here?

2024-02-23 09:30 UTC, mhellmeier commented
I suggest having a look at all the other KITs. Most KITs (what I would suggest) are using `title` along with `id` and `description`. Example from the Traceability KIT:
```
id: Architecture View Traceability Kit
title: Architecture View
description: 'Traceability Kit'
sidebar_position: 2
```

Please keep in mind to use a unique ID (not just `Architecture`), otherwise the build won't work.

2024-03-05 09:07 UTC, stephanbcbauer commented
Not sure, is there still something todo here?

2024-03-05 10:02 UTC, bcronin90 commented
Ah. I wasn't aware we explicitly linked each document again. I'll fix those links.

2024-03-05 10:37 UTC, mhellmeier approved these changes
Thanks for the fix!

2024-03-05 10:48 UTC, stephanbcbauer approved these changes
LGTM

2024-03-05 10:50 UTC, merged