PCF Kit Update Rel. 24.03
eclipse-tractusx/eclipse-tractusx.github.io pull request #710
Opened 2024-02-22 08:27 UTC by wern

Contribution from PCF Data usecase.
Updating the existing PCF Exchange Kit to it's latest Catena-X release version (now compatible with Rel. 24.03).

2024-02-22 12:30 UTC, SebastianBezold commented
Hi @wern,

could you please check, that you have an Eclipse Foundation account and signed the Eclipse Contributor Aggreement (ECA)
The email address of your EF account and the one you use for your commits have to match. 
We must not merge this with a failing ECA check

2024-02-22 15:33 UTC, wern commented
> Hi @wern,
> 
> could you please check, that you have an Eclipse Foundation account and signed the Eclipse Contributor Aggreement (ECA) The email address of your EF account and the one you use for your commits have to match. We must not merge this with a failing ECA check

Hi @SebastianBezold ,
done. ;-)

2024-02-27 14:12 UTC, maximilianong commented
Hello @wern - we tried to build your PR locally.
But we are running into dependency problems - can you have look into this?
<img width="701" alt="Screenshot 2024-02-27 at 7 40 04 PM" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/83761111/7636ad2c-b124-4074-9a43-f62033c325c4">

2024-02-27 14:57 UTC, maximilianong requested changes

2024-02-27 14:57 UTC, maximilianong commented on docs-kits/kits/PCF Exchange Kit/page_adoption-view.md
Please add a separate section for the standards - like the other KITs are doing it and add the versions e.g. https://eclipse-tractusx.github.io/docs-kits/kits/Business%20Partner%20Kit/Adoption%20View#standards

2024-02-29 07:58 UTC, SMaierTSI commented on docs-kits/kits/PCF Exchange Kit/changelog.md
> +## [1.0.0] - 2024-02-12
Changed as requested, see [b7555db](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/710/commits/b7555dbaebf0d2f11cc0c26a733514998c50b897)

2024-02-29 08:14 UTC, SMaierTSI commented on docs-kits/kits/PCF Exchange Kit/page_adoption-view.md
Changed as requested, see [287c8e5](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/710/commits/287c8e524673c9320d4bb4ec32e2dc7507d3e73d)

2024-02-29 08:28 UTC, SMaierTSI commented on docs-kits/kits/PCF Exchange Kit/page_adoption-view.md
Adapted and added standard section as requested.

2024-02-29 08:47 UTC, SMaierTSI commented on docs-kits/kits/PCF Exchange Kit/Software Development View/page_software-development-view.md
Empty operation view page deleted as requested, see [a8feb1d](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/710/commits/a8feb1df39a607b400baa354fa4384b0fa212916)

2024-02-29 08:51 UTC, SMaierTSI commented on docs-kits/kits/PCF Exchange Kit/page_adoption-view.md
Adapted in notice section as requested, see [9aec609](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/710/commits/9aec60946bbde769ed7d24230482d036c97b5313)

2024-02-29 09:03 UTC, SMaierTSI commented on docs-kits/kits/PCF Exchange Kit/Software Development View/page_software-development-view.md
>  ### Used CX Standards
@maximilianong : after discussion in our PCF use case team we would leave the standards as specified in the software development view as they represent the technical details which are probably useful for a technical audience. In our adoption view, we focus on business process/ methodological aspects, so there we only list the according general standards e.g. PCF rulebook. Would it be ok if we don't adapt this as requested by you?

2024-02-29 09:09 UTC, SMaierTSI commented on docs-kits/kits/PCF Exchange Kit/Software Development View/page_software-development-view.md
>  ## NOTICE
Adapted as requested, see [fb1d856](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/710/commits/fb1d856d36bc0eb4225518ea212fee0720ff367f)

2024-02-29 09:14 UTC, SMaierTSI commented on docs-kits/kits/PCF Exchange Kit/Software Development View/pcf-exchange-api/get-pcf.api.mdx
@maximilianong : can you please tell us if we can achieve this by just deleting the docs-kits/kits/PCF Exchange Kit/Software Development View/pcf-exchange-api/catena-x-pcf-request-endpoint.info.mdx file? If so i would delete the according file

2024-02-29 13:49 UTC, danielmiehle commented
@SMaierTSI thank you for fixing the change requests. Can you also have a look at the current linting errors, please?

![image](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/29955508/97775e1e-253c-43dd-941b-6f88677123f6)

2024-02-29 16:01 UTC, SMaierTSI commented on docs-kits/kits/PCF Exchange Kit/Software Development View/pcf-exchange-api/get-pcf.api.mdx
Thank you @SujitMBRDI , guess we will pick the 2nd option

2024-03-01 08:40 UTC, SMaierTSI commented
@danielmiehle : fixed the linting errors for the PCF Exchange KIT. However, there's still a large number of errors referring to other KITS which are not in scope of PCF Exchange

2024-03-05 15:49 UTC, wern commented on docs-kits/kits/PCF Exchange Kit/Software Development View/page_software-development-view.md
@maximilianong after deleting `operating_view.md` Docusaurus refuses to start:

> These sidebar document ids do not exist:
> - kits/PCF Exchange Kit/Operation View

Do we want to change sidebar structure here or just add `operating_view.md` with a note "No open source software available at the moment." ?

2024-03-05 16:10 UTC, wern commented on docs-kits/kits/PCF Exchange Kit/Software Development View/pcf-exchange-api/get-pcf.api.mdx
@maximilianong deleting the page is also not an option here, as it looks like Docusaurus structure will get messed up when doing so. So either we change sidebar structure here or add some info to the page like: 
"PCF Exchange API to be used to request, return or update PCF data via the Catena-X network."

2024-03-06 07:40 UTC, danielmiehle submitted a review, later dismissed

2024-03-06 07:40 UTC, maximilianong submitted a review, later dismissed

2024-03-06 13:55 UTC, maximilianong approved these changes

2024-03-06 13:55 UTC, danielmiehle approved these changes

2024-03-06 13:55 UTC, merged