docs(Business partner  kit): fixed broken link.
eclipse-tractusx/eclipse-tractusx.github.io pull request #750
Opened 2024-03-12 13:45 UTC by Unsharm

## Description
In this pull request, I have fixed the broken links in the software development view within business partner kit.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-03-13 13:22 UTC, carslen requested changes
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/77ab308f42019835d5d18c4091a43988af43273b/docs-kits/kits/Business%20Partner%20Kit/Software%20Development%20View/page_software-development-view.md?plain=1#L53-L55

Wouldn't it make sense to fix it in `/docs-kits/...` as well?

2024-03-13 13:31 UTC, Unsharm commented
@carslen yes, Sujit already informed me about it. I am adapting those changes.

2024-03-13 14:04 UTC, carslen approved these changes

2024-03-14 09:06 UTC, SujitMBRDI approved these changes
Looks good to me now

2024-03-14 13:27 UTC, merged