docs(connector-kit):icon format changed to svg
eclipse-tractusx/eclipse-tractusx.github.io pull request #774
Opened 2024-03-20 15:00 UTC by Unsharm

## Description
In this pull request, I have changed the format of the icon's image in the adoption view of the Connector kit from PNG to SVG.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-03-21 04:50 UTC, SujitMBRDI requested changes
Hello @Unsharm,
As i mentioned on other pull request [https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/773#pullrequestreview-1950745914](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/773#pullrequestreview-1950745914), for connector-kit, i can see the banner is being used on changelog page as well and not being used on operation view.
So, kindly adapt the changes on changelog page with icon you have created in svg format.

2024-03-21 04:54 UTC, SujitMBRDI commented
Hi @maximilianong,
wanted to confirm, do we need to delete old .png image from static/img folder? if yes then we need to adapt changes to old versions as well because it can loose the reference.

2024-03-21 13:13 UTC, SujitMBRDI requested changes

2024-03-21 13:26 UTC, maximilianong commented
> Hello @Unsharm, As i mentioned on other pull request [#773 (review)](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/773#pullrequestreview-1950745914), for connector-kit, i can see the banner is being used on changelog page as well and not being used on operation view. So, kindly adapt the changes on changelog page with icon you have created in svg format.

Can we do this for all KITs the same way. Icon on all main pages of a KIT.
I was not aware of this.

2024-03-21 13:27 UTC, maximilianong commented
> Hi @maximilianong, wanted to confirm, do we need to delete old .png image from static/img folder? if yes then we need to adapt changes to old versions as well because it can loose the reference.

No - that topic I discussed with @Unsharm aswell. We leave the old files where they are.

2024-03-21 13:30 UTC, SujitMBRDI commented
> > Hi @maximilianong, wanted to confirm, do we need to delete old .png image from static/img folder? if yes then we need to adapt changes to old versions as well because it can loose the reference.
> 
> No - that topic I discussed with @Unsharm aswell. We leave the old files where they are.

Cool :)

2024-03-21 13:30 UTC, Unsharm commented on docs-kits/kits/Connector Kit/page_changelog.md
> +## [2.2.0] - unreleased
> Here, version should be either [3.0.0] or [2.1.0] as in last release 24.03 version [2.0.0] is released.

@SujitMBRDI okay, I am adapting the change.

2024-03-21 13:36 UTC, SujitMBRDI commented
> > Hello @Unsharm, As i mentioned on other pull request [#773 (review)](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/773#pullrequestreview-1950745914), for connector-kit, i can see the banner is being used on changelog page as well and not being used on operation view. So, kindly adapt the changes on changelog page with icon you have created in svg format.
> 
> Can we do this for all KITs the same way. Icon on all main pages of a KIT. I was not aware of this.

I thought in a way that for other KITs where ever we see .png icon then we should replace it. 
Lets take this as example, if we don't see banner on operation view then we should ignore it but for those main pages having icon that has to be replace by .svg image
Please correct me if i am wrong here.

2024-03-21 13:57 UTC, maximilianong commented
> > > Hello @Unsharm, As i mentioned on other pull request [#773 (review)](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/773#pullrequestreview-1950745914), for connector-kit, i can see the banner is being used on changelog page as well and not being used on operation view. So, kindly adapt the changes on changelog page with icon you have created in svg format.
> > 
> > 
> > Can we do this for all KITs the same way. Icon on all main pages of a KIT. I was not aware of this.
> 
> I thought in a way that for other KITs where ever we see .png icon then we should replace it. Lets take this as example, if we don't see banner on operation view then we should ignore it but for those main pages having icon that has to be replace by .svg image Please correct me if i am wrong here.

TBH would be nice if we see that on operation view is no KIT icon - we add it.

2024-03-25 12:58 UTC, Unsharm commented on docs-kits/kits/Connector Kit/page_changelog.md
> +## [2.2.0] - unreleased
@SujitMBRDI changes has been implemented.

2024-03-25 12:59 UTC, SujitMBRDI approved these changes
LGTM

2024-03-26 07:19 UTC, maximilianong approved these changes

2024-03-26 07:19 UTC, merged