docs(behaviour-twin-Rul-kit):icon format changed to SVG
eclipse-tractusx/eclipse-tractusx.github.io pull request #786
Opened 2024-03-24 16:34 UTC by Unsharm

## Description
In this pull request, I have changed the format of the icon's image in the adoption view, operation view and changelog of the Behaviour twin Rul kit from PNG to SVG.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-03-25 12:47 UTC, SujitMBRDI requested changes
LGTM, just update .png to .svg image for specification in development view for RUL KITs

2024-03-26 05:17 UTC, Unsharm commented
> LGTM, just update .png to .svg image for specification in development view for RUL KITs

 Okay, Implementing the changes

2024-03-26 05:27 UTC, Unsharm commented
> LGTM, just update .png to .svg image for specification in development view for RUL KITs

@SujitMBRDI The changes have been implemented.

2024-03-26 07:18 UTC, maximilianong approved these changes

2024-03-26 07:18 UTC, merged