docs: add requirement to TRG-6.01
eclipse-tractusx/eclipse-tractusx.github.io pull request #816
Opened 2024-04-03 08:06 UTC by tomaszbarwicki

PR to update prerequisites of TRG-6.01 related to GitHub Chart Releaser Action as per https://github.com/helm/chart-releaser-action the `Source Branch` needs to be set to `gh-pages`.

2024-04-04 08:44 UTC, FaGru3n requested changes
little rephrase to prevent missunderstanding

2024-04-04 08:44 UTC, FaGru3n commented on docs/release/trg-6/trg-6-1.md
> +- Change `Source Branch` to `gh-pages` in your repository settings. Submit request via Otterdog, ensure following are set:
```suggestion
- Change the GitHub Pages source branch to `gh-pages` in your repository settings. Submit request via Otterdog, ensure following are set:
```

2024-04-09 09:22 UTC, FaGru3n approved these changes
LGTM

2024-04-09 10:31 UTC, SebastianBezold approved these changes

2024-04-10 07:29 UTC, merged