feat #500 update IRS api spec
eclipse-tractusx/eclipse-tractusx.github.io pull request #861
Opened 2024-04-24 13:01 UTC by ds-ext-kmassalski

## Description

- Updating link to IRS API
- removed files with API

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-04-24 13:43 UTC, ds-jhartmann requested changes

2024-04-24 13:43 UTC, ds-jhartmann commented on docs-kits/kits/Data Chain Kit/Software Development View/page_software-development-view.md
> +- [> CX-0005 Item Relationship Service API](https://eclipse-tractusx.github.io/item-relationship-service/docs/swagger-ui/index.html)
This URL should point to the IRS Standard Document CX-0005.
Please add the Link to 
`docs-kits/kits/Data Chain Kit/Software Development View/Job Api/irs-api.info.mdx`

2024-04-24 13:43 UTC, ds-jhartmann commented on docs-kits/kits/Data Chain Kit/Software Development View/Job Api/irs-api.info.mdx
Please keep this file and add the link to the Swagger API here

2024-04-29 12:09 UTC, ds-jhartmann approved these changes
LGTM

2024-04-29 12:10 UTC, mkanal approved these changes

2024-04-29 12:10 UTC, merged