doc(tutorials): duplicate tutorial structure
eclipse-tractusx/eclipse-tractusx.github.io pull request #879
Opened 2024-05-07 06:26 UTC by stephanbcbauer

## Description

This PR duplicates the current E2E Adopter Journey tutorial because we need a basis to work on the new tutorial. The old one still works. The old one will be deleted after the new one is ready.

<img width="285" alt="image" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/84396022/ae86b146-14bc-4d89-ac30-3ef27ec1a8ba">

<img width="1920" alt="image" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/84396022/3df0d245-d948-494c-881f-e9056641d18d">

<img width="1920" alt="image" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/84396022/dcdab1df-506d-4dec-9e1e-ba442c6cd120">

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-05-07 09:35 UTC, stephanbcbauer commented
> Why do we need a work in progress documentation on our live website and marking the previous one as deprecated? Why not working on the branch `doc/add-new-tutorial` and use Docusaurus Dev server (`npm start`) for rendering checks until it's finished and publish then the new version of the tutorial?

We have to make plenty of changes to the future tutorial (for the Tractus-X community days next week). This is currently only possible step by step because otherwise the pull request would be far too large, and we would have to have the changes approved by Eclipse.  Currently, 5 people are working on the tutorial at the same time. Working on a “base” is therefore expedient. Without influencing the old tutorial.

2024-05-07 10:34 UTC, SebastianBezold requested changes
Since the tutorial will not be versioned, I would move all assets to the `/static` directory. 
Maybe to a `/static/tutorial` sub-directory to have it all grouped

2024-05-07 10:34 UTC, SebastianBezold commented on docs/tutorials/e2e_deprecated/connect/assets/img.png
The filename is a bit general

2024-05-07 10:34 UTC, SebastianBezold commented on docs/tutorials/e2e_deprecated/boost/assets/components_contract_definition.png
Would it be possible to add this as `.svg`. Would allow for easier changes

2024-05-07 13:06 UTC, JohannesARENA2036 approved these changes
We should approve this branch, even if we still need to do a couple of  further updates
Thanks Johannes

2024-05-07 13:33 UTC, SebastianBezold commented
> We should approve this branch, even if we still need to do a couple of further updates Thanks Johannes

That is exactly what we should NOT do. PRs should include a finished peace, that provides value instead of just throwing junks on this repo, that are potentially finished later. I totally agree with what @carslen said. 
I also don't really understand why a tutorial is "deprecated". 
Maybe the website is just the wrong place to put this content

2024-05-07 14:38 UTC, SebastianBezold commented on docs/tutorials/e2e_deprected.md
> +Technical knowledge (Docker, Kubernetes, Helm, Terraform) to deploy components onto a kubernetes cluster and interacting with them is advised. A detailed list of tools and their supported versions is
If this should stay at least for a bit, then at least the links have to be adapted. 
I would still prefer, that this PR does delete the old and add the new on one go.

2024-05-08 07:56 UTC, carslen commented
> We should approve this branch, even if we still need to do a couple of further updates Thanks Johannes

Why should we? I would have expected arguments rather than an additional request for approval.

2024-05-08 08:33 UTC, carslen commented
> > Why do we need a work in progress documentation on our live website and marking the previous one as deprecated? Why not working on the branch `doc/add-new-tutorial` and use Docusaurus Dev server (`npm start`) for rendering checks until it's finished and publish then the new version of the tutorial?
> 
> We have to make plenty of changes to the future tutorial (for the Tractus-X community days next week). This is currently only possible step by step because otherwise the pull request would be far too large, and we would have to have the changes approved by Eclipse. Currently, 5 people are working on the tutorial at the same time. Working on a “base” is therefore expedient. Without influencing the old tutorial.

I would not count the content of a tutorial as source code. Thus, no IP Check should be necessary even if there are more than 1000 lines of changed. BTW: This PR is already > 1.000 lines of code ;)

I don't get the "5 people working on this tutorial" argument. Why can't they work on the branch this PR is opened from?

2024-05-08 15:34 UTC, stephanbcbauer commented
Thank you very much for your comments. I will delete this PR. We will create a “development” branch and merge all the changes, when we are ready.

2024-05-08 15:34 UTC, closed without merging