Feature/pcf exchange kit update rel 24 05
eclipse-tractusx/eclipse-tractusx.github.io pull request #890
Opened 2024-05-17 11:20 UTC by wern

## Description
Update of PCF Exchange Kit to Version Rel. 24.05

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-05-21 14:04 UTC, danielmiehle requested changes
Thanks for the KIT update - the SDE for PCF is a big step forward. I only have minor change request.

2024-05-21 14:04 UTC, danielmiehle commented on docs-kits/kits/PCF Exchange Kit/page_software-operation-view.md
> +In the past, the Catena-X ecosystem for PCF data exchange consisted exclusively of commercial applications (so-called COTS apps). For release 24.05, with the Simple Data Exchanger (SDE), for the firs
I would suggest to adjust the sentence to:

"In addition to certified commercial solutions, there is now also an open-source reference implementation available for the first time..."

2024-05-23 23:44 UTC, jSchuetz88 approved these changes
Only minor remarks from my side, looks good to go.

2024-05-23 23:44 UTC, jSchuetz88 commented on docs-kits/kits/PCF Exchange Kit/page_adoption-view.md
> +The standards this release will be published soon. Our relevant standards can be downloaded from the official [Catena-X Standard Library](https://catena-x.net/de/standard-library):
There seems to be something off with the first sentence. Perhaps "The standard **of** this ..."

2024-05-24 07:08 UTC, danielmiehle commented
@wern: Can you please add the changes requests asap. We would like to merge the PR today. Thank you!

2024-05-24 11:19 UTC, wern commented
@danielmiehle Review finding fixed.

2024-05-24 11:41 UTC, danielmiehle approved these changes

2024-05-24 11:41 UTC, maximilianong approved these changes

2024-05-24 11:43 UTC, danielmiehle commented
@wern: Thanks! Can you also fix the conflicting files asap?

2024-05-27 08:36 UTC, wern commented
@danielmiehle @HFocken Trying to check locally, but as there seems to be broken line endings in the repo (outside our changes) it may take some time...

2024-05-27 08:44 UTC, danielmiehle commented
> @danielmiehle @HFocken Trying to check locally, but as there seem to be broken line endings in the repo (outside our changes) it may take some time...

Thank you for checking!

2024-05-27 09:56 UTC, wern commented
@danielmiehle @HFocken I may be too stupid, but I am not able to resolve the merge conflicts without changing stuff outside of our kit (due to broken, checked in line feeds). Please let me know how we want to proceed here.

2024-05-27 11:30 UTC, danielmiehle commented
> @danielmiehle @HFocken I may be too stupid, but I am not able to resolve the merge conflicts without changing stuff outside of our kit (due to broken, checked in line feeds). Please let me know how we want to proceed here.

Please, contact johann.schuetz@catena-x.net for further support.
fyi, @jSchuetz88

2024-05-27 15:44 UTC, danielmiehle commented
@wern: so we can close this PR, right?

2024-05-27 15:46 UTC, closed without merging