docs: adjust trg 5 05 ingress exampe
eclipse-tractusx/eclipse-tractusx.github.io pull request #896
Opened 2024-05-24 11:14 UTC by almadigabor

## Description

Use empty slice to be albe to create ingress with tls disabled.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-05-27 20:03 UTC, evegufy approved these changes

2024-05-29 11:33 UTC, evegufy requested changes
I had a quick look again and I think the commented out example part could be improved, I didn't notice this [here](https://github.com/eclipse-tractusx/sd-factory/commit/e491fc1d28e4ae2b54891ea7d2b50e8b750e12c8) (from where you got it from), as I just wanted to get rid of the preset in the values.yaml. But as a TRG example [this](https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/v1.0.0/charts/ssi-credential-issuer/values.yaml#L254) would be more appropriate

2024-05-30 06:35 UTC, almadigabor commented
> I had a quick look again and I think the commented out example part could be improved, I didn't notice this [here](https://github.com/eclipse-tractusx/sd-factory/commit/e491fc1d28e4ae2b54891ea7d2b50e8b750e12c8) (from where you got it from), as I just wanted to get rid of the preset in the values.yaml. But as a TRG example [this](https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/v1.0.0/charts/ssi-credential-issuer/values.yaml#L254) would be more appropriate

Hey @evegufy, good point. I adjusted the example so it's more aligned with the syntax of the ingress manifest.

2024-06-04 09:56 UTC, tomaszbarwicki approved these changes

2024-06-04 11:23 UTC, merged