Traceability: Upate to latest (2408) DataExchangeGovernance
eclipse-tractusx/eclipse-tractusx.github.io pull request #922
Opened 2024-06-07 09:28 UTC by matgnt

Instead of use case specific legal documents / credentials, there is now a single consolidated document and consquently also a single Verifiable Credential. Policies need to be updated accordingly.

2024-06-07 10:01 UTC, matgnt commented
cc: @DanielaWuensch

2024-06-10 09:17 UTC, mhellmeier requested changes

2024-06-11 19:59 UTC, mhellmeier approved these changes

2024-06-13 19:23 UTC, arnoweiss approved these changes

2024-06-13 19:23 UTC, merged