docs: security office hour meeting minutes 2024-06-20
eclipse-tractusx/eclipse-tractusx.github.io pull request #941
Opened 2024-06-20 14:38 UTC by RoKrish14

## Description
Adding the security office hour meeting minutes for 2024-06-20.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-06-24 08:31 UTC, FaGru3n requested changes
LGTM, page could be build and info´s are related to consortia env...

Maybe marking theese info´s as former GitHub Organisation `Catenax-ng` without mentioning the to be "read-only" org... 

... just a little reminder to you @RoKrish14 with committer permission you could create a little branch directly within the upstream repo on https://github.com/eclipse-tractusx/eclipse-tractusx.github.io makes it a bit easier to validate the changes to our meeting minutes section.

2024-06-25 08:01 UTC, RoKrish14 commented
> LGTM, page could be build and info´s are related to consortia env...
> 
> Maybe marking theese info´s as former GitHub Organisation `Catenax-ng` without mentioning the to be "read-only" org...
> 
> ... just a little reminder to you @RoKrish14 with committer permission you could create a little branch directly within the upstream repo on https://github.com/eclipse-tractusx/eclipse-tractusx.github.io makes it a bit easier to validate the changes to our meeting minutes section.

The changes are placed and thanks @FaGru3n for the hint. 
I will do so for the next meeting minutes.

2024-06-26 12:41 UTC, FaGru3n approved these changes
Thx for the update 😉

2024-07-09 10:45 UTC, almadigabor approved these changes

2024-07-13 20:48 UTC, merged