docs: Update trg-8-04.md
eclipse-tractusx/eclipse-tractusx.github.io pull request #949
Opened 2024-06-27 06:41 UTC by klaudiaZF

Small update of Trivy workflow

## Description

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-06-27 07:32 UTC, RoKrish14 requested changes

2024-06-27 07:32 UTC, RoKrish14 commented on docs/release/trg-8/trg-8-04.md
> -          hide-progress: false
Please dont remove this. Let it stay after the line 
`severity: "CRITICAL,HIGH"`

2024-06-27 07:40 UTC, RoKrish14 commented
@klaudiaZF : Please update the description for this PR: The modification in the workflow ensures that the SARIF report generated by Trivy only includes vulnerabilities with the specified severity levels ("CRITICAL" and "HIGH" in this case). The build fails if any such vulnerabilities are found, prompting immediate action to resolve them

2024-07-04 04:18 UTC, florianrusch-zf approved these changes

2024-07-05 07:42 UTC, RoKrish14 approved these changes
LGTM
Thank You @klaudiaZF

2024-07-05 07:43 UTC, merged